version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/careerhub
      - JWT_SECRET=your-super-secret-key-change-in-production
      - JWT_EXPIRES_IN=3600
      - REFRESH_TOKEN_EXPIRES_IN=604800
      - PORT=3000
      - ENVIRONMENT=development
      - RUST_LOG=info
    depends_on:
      - db
    volumes:
      - ./:/usr/src/app
      - cargo-cache:/usr/local/cargo/registry
      - target-cache:/usr/src/app/target

  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=careerhub
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
  cargo-cache:
  target-cache: 